// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package com.wyltek.wallet.core.native

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_wyltekwalletcore_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_wyltekwalletcore_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "wyltekwalletcore"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "wyltekwalletcore"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_wyltekwalletcore_checksum_func_wallet_version(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_decode_address(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_encode_address(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_validate_address(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_blake2b_256(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_ckb_hash(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_generate_secp256k1_keypair(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_public_key_to_ckb_address(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_public_key_to_pq_address(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_generate_mnemonic(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_get_bip39_wordlist(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_mnemonic_to_seed(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_suggest_bip39_words(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_validate_mnemonic(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_generate_mldsa65_keypair(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_mldsa65_from_seed(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_mldsa65_lock_args_v2(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_mldsa65_sign(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_mldsa65_verify(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_pq_lock_args(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_mldsa65_witness_placeholder_hex(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_sign_ckb_mldsa65(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_sign_ckb_secp256k1(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_sign_ckb_secp256k1_dao_witness(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_sign_ckb_secp256k1_witness(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_sign_message(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_sign_transaction(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_verify_signature(
    ): Short
    external fun uniffi_wyltekwalletcore_checksum_func_build_transaction(
    ): Short
    external fun ffi_wyltekwalletcore_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "wyltekwalletcore"))
        
    }
    external fun uniffi_wyltekwalletcore_fn_func_wallet_version(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_decode_address(`address`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_encode_address(`codeHash`: RustBuffer.ByValue,`hashType`: RustBuffer.ByValue,`args`: RustBuffer.ByValue,`network`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_validate_address(`address`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Byte
external fun uniffi_wyltekwalletcore_fn_func_blake2b_256(`dataHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_ckb_hash(`dataHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_generate_secp256k1_keypair(`seedHex`: RustBuffer.ByValue,`derivationPath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_public_key_to_ckb_address(`publicKeyHex`: RustBuffer.ByValue,`network`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_public_key_to_pq_address(`publicKeyHex`: RustBuffer.ByValue,`network`: RustBuffer.ByValue,`algorithmId`: Byte,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_generate_mnemonic(`wordCount`: Int,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_get_bip39_wordlist(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_mnemonic_to_seed(`mnemonic`: RustBuffer.ByValue,`passphrase`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_suggest_bip39_words(`prefix`: RustBuffer.ByValue,`limit`: Int,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_validate_mnemonic(`mnemonic`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Byte
external fun uniffi_wyltekwalletcore_fn_func_generate_mldsa65_keypair(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_mldsa65_from_seed(`seedHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_mldsa65_lock_args_v2(`publicKeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_mldsa65_sign(`messageHex`: RustBuffer.ByValue,`privateKeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_mldsa65_verify(`messageHex`: RustBuffer.ByValue,`signatureHex`: RustBuffer.ByValue,`publicKeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Byte
external fun uniffi_wyltekwalletcore_fn_func_pq_lock_args(`publicKeyHex`: RustBuffer.ByValue,`algorithmId`: Byte,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_mldsa65_witness_placeholder_hex(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_sign_ckb_mldsa65(`txHashHex`: RustBuffer.ByValue,`inputs`: RustBuffer.ByValue,`privateKeyHex`: RustBuffer.ByValue,`publicKeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_sign_ckb_secp256k1(`txHashHex`: RustBuffer.ByValue,`witnessPlaceholdersHex`: RustBuffer.ByValue,`privateKeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_sign_ckb_secp256k1_dao_witness(`txHashHex`: RustBuffer.ByValue,`numInputs`: Int,`depositHeaderIndex`: Long,`privateKeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_sign_ckb_secp256k1_witness(`txHashHex`: RustBuffer.ByValue,`numInputs`: Int,`privateKeyHex`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_sign_message(`messageHex`: RustBuffer.ByValue,`privateKeyHex`: RustBuffer.ByValue,`algorithm`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_sign_transaction(`rawTxHex`: RustBuffer.ByValue,`privateKeyHex`: RustBuffer.ByValue,`algorithm`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun uniffi_wyltekwalletcore_fn_func_verify_signature(`messageHex`: RustBuffer.ByValue,`signatureHex`: RustBuffer.ByValue,`publicKeyHex`: RustBuffer.ByValue,`algorithm`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Byte
external fun uniffi_wyltekwalletcore_fn_func_build_transaction(`request`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun ffi_wyltekwalletcore_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun ffi_wyltekwalletcore_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun ffi_wyltekwalletcore_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Unit
external fun ffi_wyltekwalletcore_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun ffi_wyltekwalletcore_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_cancel_u8(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_free_u8(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
external fun ffi_wyltekwalletcore_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_cancel_i8(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_free_i8(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
external fun ffi_wyltekwalletcore_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_cancel_u16(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_free_u16(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
external fun ffi_wyltekwalletcore_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_cancel_i16(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_free_i16(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
external fun ffi_wyltekwalletcore_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_cancel_u32(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_free_u32(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
external fun ffi_wyltekwalletcore_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_cancel_i32(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_free_i32(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
external fun ffi_wyltekwalletcore_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_cancel_u64(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_free_u64(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
external fun ffi_wyltekwalletcore_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_cancel_i64(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_free_i64(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
external fun ffi_wyltekwalletcore_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_cancel_f32(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_free_f32(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Float
external fun ffi_wyltekwalletcore_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_cancel_f64(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_free_f64(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Double
external fun ffi_wyltekwalletcore_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_cancel_rust_buffer(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_free_rust_buffer(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
external fun ffi_wyltekwalletcore_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_cancel_void(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_free_void(`handle`: Long,
): Unit
external fun ffi_wyltekwalletcore_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit

    
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_wyltekwalletcore_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_wyltekwalletcore_checksum_func_wallet_version() != 39156.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_decode_address() != 62949.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_encode_address() != 26272.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_validate_address() != 52759.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_blake2b_256() != 26658.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_ckb_hash() != 27088.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_generate_secp256k1_keypair() != 40314.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_public_key_to_ckb_address() != 38397.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_public_key_to_pq_address() != 37766.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_generate_mnemonic() != 43756.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_get_bip39_wordlist() != 798.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_mnemonic_to_seed() != 18613.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_suggest_bip39_words() != 59106.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_validate_mnemonic() != 360.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_generate_mldsa65_keypair() != 43443.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_mldsa65_from_seed() != 65027.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_mldsa65_lock_args_v2() != 3289.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_mldsa65_sign() != 9642.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_mldsa65_verify() != 50642.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_pq_lock_args() != 10651.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_mldsa65_witness_placeholder_hex() != 59935.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_sign_ckb_mldsa65() != 3907.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_sign_ckb_secp256k1() != 35672.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_sign_ckb_secp256k1_dao_witness() != 29228.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_sign_ckb_secp256k1_witness() != 18497.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_sign_message() != 35259.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_sign_transaction() != 41836.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_verify_signature() != 44663.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_wyltekwalletcore_checksum_func_build_transaction() != 20828.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle

/**
 * @suppress
 */
public object FfiConverterUByte: FfiConverter<UByte, Byte> {
    override fun lift(value: Byte): UByte {
        return value.toUByte()
    }

    override fun read(buf: ByteBuffer): UByte {
        return lift(buf.get())
    }

    override fun lower(value: UByte): Byte {
        return value.toByte()
    }

    override fun allocationSize(value: UByte) = 1UL

    override fun write(value: UByte, buf: ByteBuffer) {
        buf.put(value.toByte())
    }
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



data class AddressInfo (
    var `bech32m`: kotlin.String
    , 
    var `network`: kotlin.String
    , 
    var `formatVersion`: kotlin.String
    , 
    var `lockCodeHash`: kotlin.String
    , 
    var `lockHashType`: kotlin.String
    , 
    var `lockArgs`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeAddressInfo: FfiConverterRustBuffer<AddressInfo> {
    override fun read(buf: ByteBuffer): AddressInfo {
        return AddressInfo(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: AddressInfo) = (
            FfiConverterString.allocationSize(value.`bech32m`) +
            FfiConverterString.allocationSize(value.`network`) +
            FfiConverterString.allocationSize(value.`formatVersion`) +
            FfiConverterString.allocationSize(value.`lockCodeHash`) +
            FfiConverterString.allocationSize(value.`lockHashType`) +
            FfiConverterString.allocationSize(value.`lockArgs`)
    )

    override fun write(value: AddressInfo, buf: ByteBuffer) {
            FfiConverterString.write(value.`bech32m`, buf)
            FfiConverterString.write(value.`network`, buf)
            FfiConverterString.write(value.`formatVersion`, buf)
            FfiConverterString.write(value.`lockCodeHash`, buf)
            FfiConverterString.write(value.`lockHashType`, buf)
            FfiConverterString.write(value.`lockArgs`, buf)
    }
}



data class BuiltTransaction (
    var `rawTransactionHex`: kotlin.String
    , 
    var `txHashHex`: kotlin.String
    , 
    var `estimatedFee`: kotlin.ULong
    , 
    var `totalInputCapacity`: kotlin.ULong
    , 
    var `totalOutputCapacity`: kotlin.ULong
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeBuiltTransaction: FfiConverterRustBuffer<BuiltTransaction> {
    override fun read(buf: ByteBuffer): BuiltTransaction {
        return BuiltTransaction(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: BuiltTransaction) = (
            FfiConverterString.allocationSize(value.`rawTransactionHex`) +
            FfiConverterString.allocationSize(value.`txHashHex`) +
            FfiConverterULong.allocationSize(value.`estimatedFee`) +
            FfiConverterULong.allocationSize(value.`totalInputCapacity`) +
            FfiConverterULong.allocationSize(value.`totalOutputCapacity`)
    )

    override fun write(value: BuiltTransaction, buf: ByteBuffer) {
            FfiConverterString.write(value.`rawTransactionHex`, buf)
            FfiConverterString.write(value.`txHashHex`, buf)
            FfiConverterULong.write(value.`estimatedFee`, buf)
            FfiConverterULong.write(value.`totalInputCapacity`, buf)
            FfiConverterULong.write(value.`totalOutputCapacity`, buf)
    }
}



data class KeyPair (
    var `publicKeyHex`: kotlin.String
    , 
    var `privateKeyHex`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeKeyPair: FfiConverterRustBuffer<KeyPair> {
    override fun read(buf: ByteBuffer): KeyPair {
        return KeyPair(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: KeyPair) = (
            FfiConverterString.allocationSize(value.`publicKeyHex`) +
            FfiConverterString.allocationSize(value.`privateKeyHex`)
    )

    override fun write(value: KeyPair, buf: ByteBuffer) {
            FfiConverterString.write(value.`publicKeyHex`, buf)
            FfiConverterString.write(value.`privateKeyHex`, buf)
    }
}



/**
 * A live input cell being spent, as needed to reconstruct the CighashAll
 * stream off-chain. `data` is hex (empty / "0x" for a pure-CKB cell).
 */
data class MldsaInputCell (
    var `capacity`: kotlin.ULong
    , 
    var `lockCodeHash`: kotlin.String
    , 
    var `lockHashType`: kotlin.String
    , 
    var `lockArgs`: kotlin.String
    , 
    var `data`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeMldsaInputCell: FfiConverterRustBuffer<MldsaInputCell> {
    override fun read(buf: ByteBuffer): MldsaInputCell {
        return MldsaInputCell(
            FfiConverterULong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: MldsaInputCell) = (
            FfiConverterULong.allocationSize(value.`capacity`) +
            FfiConverterString.allocationSize(value.`lockCodeHash`) +
            FfiConverterString.allocationSize(value.`lockHashType`) +
            FfiConverterString.allocationSize(value.`lockArgs`) +
            FfiConverterString.allocationSize(value.`data`)
    )

    override fun write(value: MldsaInputCell, buf: ByteBuffer) {
            FfiConverterULong.write(value.`capacity`, buf)
            FfiConverterString.write(value.`lockCodeHash`, buf)
            FfiConverterString.write(value.`lockHashType`, buf)
            FfiConverterString.write(value.`lockArgs`, buf)
            FfiConverterString.write(value.`data`, buf)
    }
}



data class MnemonicResult (
    var `mnemonic`: kotlin.String
    , 
    var `seedHex`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeMnemonicResult: FfiConverterRustBuffer<MnemonicResult> {
    override fun read(buf: ByteBuffer): MnemonicResult {
        return MnemonicResult(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: MnemonicResult) = (
            FfiConverterString.allocationSize(value.`mnemonic`) +
            FfiConverterString.allocationSize(value.`seedHex`)
    )

    override fun write(value: MnemonicResult, buf: ByteBuffer) {
            FfiConverterString.write(value.`mnemonic`, buf)
            FfiConverterString.write(value.`seedHex`, buf)
    }
}



data class PqKeyPair (
    var `publicKeyHex`: kotlin.String
    , 
    var `privateKeyHex`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePQKeyPair: FfiConverterRustBuffer<PqKeyPair> {
    override fun read(buf: ByteBuffer): PqKeyPair {
        return PqKeyPair(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: PqKeyPair) = (
            FfiConverterString.allocationSize(value.`publicKeyHex`) +
            FfiConverterString.allocationSize(value.`privateKeyHex`)
    )

    override fun write(value: PqKeyPair, buf: ByteBuffer) {
            FfiConverterString.write(value.`publicKeyHex`, buf)
            FfiConverterString.write(value.`privateKeyHex`, buf)
    }
}



data class TransactionRequest (
    var `inputs`: List<TxInput>
    , 
    var `outputs`: List<TxOutput>
    , 
    var `cellDeps`: List<TxCellDep>
    , 
    /**
     * Block hashes referenced as header_deps (e.g. NervosDAO deposit/withdraw
     * headers). MUST be included so the hashed RawTransaction — and therefore
     * the signing tx_hash — matches the broadcast transaction.
     */
    var `headerDeps`: List<kotlin.String> = listOf() 
    , 
    var `feeRate`: kotlin.ULong
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTransactionRequest: FfiConverterRustBuffer<TransactionRequest> {
    override fun read(buf: ByteBuffer): TransactionRequest {
        return TransactionRequest(
            FfiConverterSequenceTypeTxInput.read(buf),
            FfiConverterSequenceTypeTxOutput.read(buf),
            FfiConverterSequenceTypeTxCellDep.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: TransactionRequest) = (
            FfiConverterSequenceTypeTxInput.allocationSize(value.`inputs`) +
            FfiConverterSequenceTypeTxOutput.allocationSize(value.`outputs`) +
            FfiConverterSequenceTypeTxCellDep.allocationSize(value.`cellDeps`) +
            FfiConverterSequenceString.allocationSize(value.`headerDeps`) +
            FfiConverterULong.allocationSize(value.`feeRate`)
    )

    override fun write(value: TransactionRequest, buf: ByteBuffer) {
            FfiConverterSequenceTypeTxInput.write(value.`inputs`, buf)
            FfiConverterSequenceTypeTxOutput.write(value.`outputs`, buf)
            FfiConverterSequenceTypeTxCellDep.write(value.`cellDeps`, buf)
            FfiConverterSequenceString.write(value.`headerDeps`, buf)
            FfiConverterULong.write(value.`feeRate`, buf)
    }
}



data class TxCellDep (
    var `txHash`: kotlin.String
    , 
    var `index`: kotlin.UInt
    , 
    var `depType`: kotlin.UByte
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTxCellDep: FfiConverterRustBuffer<TxCellDep> {
    override fun read(buf: ByteBuffer): TxCellDep {
        return TxCellDep(
            FfiConverterString.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUByte.read(buf),
        )
    }

    override fun allocationSize(value: TxCellDep) = (
            FfiConverterString.allocationSize(value.`txHash`) +
            FfiConverterUInt.allocationSize(value.`index`) +
            FfiConverterUByte.allocationSize(value.`depType`)
    )

    override fun write(value: TxCellDep, buf: ByteBuffer) {
            FfiConverterString.write(value.`txHash`, buf)
            FfiConverterUInt.write(value.`index`, buf)
            FfiConverterUByte.write(value.`depType`, buf)
    }
}



data class TxInput (
    var `txHash`: kotlin.String
    , 
    var `index`: kotlin.UInt
    , 
    var `since`: kotlin.ULong
    , 
    var `capacity`: kotlin.ULong
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTxInput: FfiConverterRustBuffer<TxInput> {
    override fun read(buf: ByteBuffer): TxInput {
        return TxInput(
            FfiConverterString.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: TxInput) = (
            FfiConverterString.allocationSize(value.`txHash`) +
            FfiConverterUInt.allocationSize(value.`index`) +
            FfiConverterULong.allocationSize(value.`since`) +
            FfiConverterULong.allocationSize(value.`capacity`)
    )

    override fun write(value: TxInput, buf: ByteBuffer) {
            FfiConverterString.write(value.`txHash`, buf)
            FfiConverterUInt.write(value.`index`, buf)
            FfiConverterULong.write(value.`since`, buf)
            FfiConverterULong.write(value.`capacity`, buf)
    }
}



data class TxOutput (
    var `capacity`: kotlin.ULong
    , 
    var `lockCodeHash`: kotlin.String
    , 
    var `lockHashType`: kotlin.String
    , 
    var `lockArgs`: kotlin.String
    , 
    var `typeCodeHash`: kotlin.String
    , 
    var `typeHashType`: kotlin.String
    , 
    var `typeArgs`: kotlin.String
    , 
    var `data`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeTxOutput: FfiConverterRustBuffer<TxOutput> {
    override fun read(buf: ByteBuffer): TxOutput {
        return TxOutput(
            FfiConverterULong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: TxOutput) = (
            FfiConverterULong.allocationSize(value.`capacity`) +
            FfiConverterString.allocationSize(value.`lockCodeHash`) +
            FfiConverterString.allocationSize(value.`lockHashType`) +
            FfiConverterString.allocationSize(value.`lockArgs`) +
            FfiConverterString.allocationSize(value.`typeCodeHash`) +
            FfiConverterString.allocationSize(value.`typeHashType`) +
            FfiConverterString.allocationSize(value.`typeArgs`) +
            FfiConverterString.allocationSize(value.`data`)
    )

    override fun write(value: TxOutput, buf: ByteBuffer) {
            FfiConverterULong.write(value.`capacity`, buf)
            FfiConverterString.write(value.`lockCodeHash`, buf)
            FfiConverterString.write(value.`lockHashType`, buf)
            FfiConverterString.write(value.`lockArgs`, buf)
            FfiConverterString.write(value.`typeCodeHash`, buf)
            FfiConverterString.write(value.`typeHashType`, buf)
            FfiConverterString.write(value.`typeArgs`, buf)
            FfiConverterString.write(value.`data`, buf)
    }
}





sealed class WalletException(message: String): kotlin.Exception(message) {
        
        class InvalidInput(message: String) : WalletException(message)
        
        class CryptoException(message: String) : WalletException(message)
        
        class EncodingException(message: String) : WalletException(message)
        

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<WalletException> {
        override fun lift(error_buf: RustBuffer.ByValue): WalletException = FfiConverterTypeWalletError.lift(error_buf)
    }
}

/**
 * @suppress
 */
public object FfiConverterTypeWalletError : FfiConverterRustBuffer<WalletException> {
    override fun read(buf: ByteBuffer): WalletException {
        
            return when(buf.getInt()) {
            1 -> WalletException.InvalidInput(FfiConverterString.read(buf))
            2 -> WalletException.CryptoException(FfiConverterString.read(buf))
            3 -> WalletException.EncodingException(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
        
    }

    override fun allocationSize(value: WalletException): ULong {
        return 4UL
    }

    override fun write(value: WalletException, buf: ByteBuffer) {
        when(value) {
            is WalletException.InvalidInput -> {
                buf.putInt(1)
                Unit
            }
            is WalletException.CryptoException -> {
                buf.putInt(2)
                Unit
            }
            is WalletException.EncodingException -> {
                buf.putInt(3)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeMldsaInputCell: FfiConverterRustBuffer<List<MldsaInputCell>> {
    override fun read(buf: ByteBuffer): List<MldsaInputCell> {
        val len = buf.getInt()
        return List<MldsaInputCell>(len) {
            FfiConverterTypeMldsaInputCell.read(buf)
        }
    }

    override fun allocationSize(value: List<MldsaInputCell>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeMldsaInputCell.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<MldsaInputCell>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeMldsaInputCell.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeTxCellDep: FfiConverterRustBuffer<List<TxCellDep>> {
    override fun read(buf: ByteBuffer): List<TxCellDep> {
        val len = buf.getInt()
        return List<TxCellDep>(len) {
            FfiConverterTypeTxCellDep.read(buf)
        }
    }

    override fun allocationSize(value: List<TxCellDep>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeTxCellDep.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<TxCellDep>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeTxCellDep.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeTxInput: FfiConverterRustBuffer<List<TxInput>> {
    override fun read(buf: ByteBuffer): List<TxInput> {
        val len = buf.getInt()
        return List<TxInput>(len) {
            FfiConverterTypeTxInput.read(buf)
        }
    }

    override fun allocationSize(value: List<TxInput>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeTxInput.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<TxInput>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeTxInput.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeTxOutput: FfiConverterRustBuffer<List<TxOutput>> {
    override fun read(buf: ByteBuffer): List<TxOutput> {
        val len = buf.getInt()
        return List<TxOutput>(len) {
            FfiConverterTypeTxOutput.read(buf)
        }
    }

    override fun allocationSize(value: List<TxOutput>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeTxOutput.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<TxOutput>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeTxOutput.write(it, buf)
        }
    }
} fun `walletVersion`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_wallet_version(
    
        _status)
}
    )
    }
    

    @Throws(WalletException::class) fun `decodeAddress`(`address`: kotlin.String): AddressInfo {
            return FfiConverterTypeAddressInfo.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_decode_address(
    
        FfiConverterString.lower(`address`),_status)
}
    )
    }
    

    @Throws(WalletException::class) fun `encodeAddress`(`codeHash`: kotlin.String, `hashType`: kotlin.String, `args`: kotlin.String, `network`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_encode_address(
    
        FfiConverterString.lower(`codeHash`),FfiConverterString.lower(`hashType`),FfiConverterString.lower(`args`),FfiConverterString.lower(`network`),_status)
}
    )
    }
    
 fun `validateAddress`(`address`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_validate_address(
    
        FfiConverterString.lower(`address`),_status)
}
    )
    }
    

    @Throws(WalletException::class) fun `blake2b256`(`dataHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_blake2b_256(
    
        FfiConverterString.lower(`dataHex`),_status)
}
    )
    }
    

    @Throws(WalletException::class) fun `ckbHash`(`dataHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_ckb_hash(
    
        FfiConverterString.lower(`dataHex`),_status)
}
    )
    }
    

    @Throws(WalletException::class) fun `generateSecp256k1Keypair`(`seedHex`: kotlin.String, `derivationPath`: kotlin.String): KeyPair {
            return FfiConverterTypeKeyPair.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_generate_secp256k1_keypair(
    
        FfiConverterString.lower(`seedHex`),FfiConverterString.lower(`derivationPath`),_status)
}
    )
    }
    

    @Throws(WalletException::class) fun `publicKeyToCkbAddress`(`publicKeyHex`: kotlin.String, `network`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_public_key_to_ckb_address(
    
        FfiConverterString.lower(`publicKeyHex`),FfiConverterString.lower(`network`),_status)
}
    )
    }
    

    @Throws(WalletException::class) fun `publicKeyToPqAddress`(`publicKeyHex`: kotlin.String, `network`: kotlin.String, `algorithmId`: kotlin.UByte): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_public_key_to_pq_address(
    
        FfiConverterString.lower(`publicKeyHex`),FfiConverterString.lower(`network`),FfiConverterUByte.lower(`algorithmId`),_status)
}
    )
    }
    

    @Throws(WalletException::class) fun `generateMnemonic`(`wordCount`: kotlin.UInt): MnemonicResult {
            return FfiConverterTypeMnemonicResult.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_generate_mnemonic(
    
        FfiConverterUInt.lower(`wordCount`),_status)
}
    )
    }
    
 fun `getBip39Wordlist`(): List<kotlin.String> {
            return FfiConverterSequenceString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_get_bip39_wordlist(
    
        _status)
}
    )
    }
    

    @Throws(WalletException::class) fun `mnemonicToSeed`(`mnemonic`: kotlin.String, `passphrase`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_mnemonic_to_seed(
    
        FfiConverterString.lower(`mnemonic`),FfiConverterString.lower(`passphrase`),_status)
}
    )
    }
    
 fun `suggestBip39Words`(`prefix`: kotlin.String, `limit`: kotlin.UInt): List<kotlin.String> {
            return FfiConverterSequenceString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_suggest_bip39_words(
    
        FfiConverterString.lower(`prefix`),FfiConverterUInt.lower(`limit`),_status)
}
    )
    }
    
 fun `validateMnemonic`(`mnemonic`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_validate_mnemonic(
    
        FfiConverterString.lower(`mnemonic`),_status)
}
    )
    }
    

    @Throws(WalletException::class) fun `generateMldsa65Keypair`(): PqKeyPair {
            return FfiConverterTypePQKeyPair.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_generate_mldsa65_keypair(
    
        _status)
}
    )
    }
    

    @Throws(WalletException::class) fun `mldsa65FromSeed`(`seedHex`: kotlin.String): PqKeyPair {
            return FfiConverterTypePQKeyPair.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_mldsa65_from_seed(
    
        FfiConverterString.lower(`seedHex`),_status)
}
    )
    }
    

        /**
         * Build the 37-byte lock args for the deployed `mldsa65-lock-v2-rust`
         * contract (code_hash 0xd70653f7…78a4).
         * Layout: [0x80, 0x01, 0x01, 0x01, flag, blake2b256_personal("ckb-mldsa-sct", pubkey)]
         * where flag = (param_id(61) << 1) | has_signature(0) = 0x7a.
         * Matches contracts/mldsa-lock-v2-rust/src/{entry,helpers}.rs in
         * toastmanAu/ckb-mldsa-lock — NOT the legacy C lock the JS SDK targets.
         */
    @Throws(WalletException::class) fun `mldsa65LockArgsV2`(`publicKeyHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_mldsa65_lock_args_v2(
    
        FfiConverterString.lower(`publicKeyHex`),_status)
}
    )
    }
    

    @Throws(WalletException::class) fun `mldsa65Sign`(`messageHex`: kotlin.String, `privateKeyHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_mldsa65_sign(
    
        FfiConverterString.lower(`messageHex`),FfiConverterString.lower(`privateKeyHex`),_status)
}
    )
    }
    

    @Throws(WalletException::class) fun `mldsa65Verify`(`messageHex`: kotlin.String, `signatureHex`: kotlin.String, `publicKeyHex`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_mldsa65_verify(
    
        FfiConverterString.lower(`messageHex`),FfiConverterString.lower(`signatureHex`),FfiConverterString.lower(`publicKeyHex`),_status)
}
    )
    }
    

    @Throws(WalletException::class) fun `pqLockArgs`(`publicKeyHex`: kotlin.String, `algorithmId`: kotlin.UByte): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_pq_lock_args(
    
        FfiConverterString.lower(`publicKeyHex`),FfiConverterUByte.lower(`algorithmId`),_status)
}
    )
    }
    

        /**
         * Pre-signing witness placeholder of the exact size of the final WitnessArgs,
         * for fee sizing. WitnessArgs(lock = [flag | pubkey | sig]).
         */ fun `mldsa65WitnessPlaceholderHex`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_mldsa65_witness_placeholder_hex(
    
        _status)
}
    )
    }
    

        /**
         * Sign a CKB transaction for the deployed `mldsa65-lock-v2-rust` contract.
         * Returns the fully-formed WitnessArgs hex (no `0x` prefix) for witnesses[0].
         *
         * tx_hash_hex:     32-byte raw-transaction hash (from `build_transaction`).
         * inputs:          every input cell being spent (all locked by this PQ lock).
         * private_key_hex: 4032-byte ML-DSA-65 secret key.
         * public_key_hex:  1952-byte ML-DSA-65 public key (embedded flat in the lock).
         */
    @Throws(WalletException::class) fun `signCkbMldsa65`(`txHashHex`: kotlin.String, `inputs`: List<MldsaInputCell>, `privateKeyHex`: kotlin.String, `publicKeyHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_sign_ckb_mldsa65(
    
        FfiConverterString.lower(`txHashHex`),FfiConverterSequenceTypeMldsaInputCell.lower(`inputs`),FfiConverterString.lower(`privateKeyHex`),FfiConverterString.lower(`publicKeyHex`),_status)
}
    )
    }
    

        /**
         * Sign a CKB SECP256K1_BLAKE160_SIGHASH_ALL transaction.
         * tx_hash_hex: the transaction hash (32 bytes, hex)
         * witness_placeholders_hex: list of witness data as hex strings.
         * For the input group being signed, the first witness should be a 65-byte placeholder.
         * Other witnesses in the same group should be empty ("0x").
         * private_key_hex: secp256k1 private key (32 bytes, hex)
         * Returns: 65-byte recoverable signature as hex string.
         */
    @Throws(WalletException::class) fun `signCkbSecp256k1`(`txHashHex`: kotlin.String, `witnessPlaceholdersHex`: List<kotlin.String>, `privateKeyHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_sign_ckb_secp256k1(
    
        FfiConverterString.lower(`txHashHex`),FfiConverterSequenceString.lower(`witnessPlaceholdersHex`),FfiConverterString.lower(`privateKeyHex`),_status)
}
    )
    }
    

        /**
         * NervosDAO phase-2 (unlock/claim) witness builder. The withdrawing cell's
         * `witnesses[0]` must carry the secp signature (lock) AND an `input_type`
         * field = the u64 LE index of the deposit block header within header_deps.
         *
         * Assumes the withdrawing cell is input 0 of a single secp group. The sighash
         * is computed over the WitnessArgs with its lock zeroed but `input_type`
         * PRESENT (the index is part of the signed message).
         */
    @Throws(WalletException::class) fun `signCkbSecp256k1DaoWitness`(`txHashHex`: kotlin.String, `numInputs`: kotlin.UInt, `depositHeaderIndex`: kotlin.ULong, `privateKeyHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_sign_ckb_secp256k1_dao_witness(
    
        FfiConverterString.lower(`txHashHex`),FfiConverterUInt.lower(`numInputs`),FfiConverterULong.lower(`depositHeaderIndex`),FfiConverterString.lower(`privateKeyHex`),_status)
}
    )
    }
    

        /**
         * secp256k1_blake160_sighash_all witness builder. Computes the canonical CKB
         * sighash and returns the FULL `WitnessArgs(lock = 65-byte recoverable sig)`
         * hex (no `0x`) to drop straight into witnesses[0].
         *
         * The standard lock expects: message =
         * ckbhash(tx_hash || u64le(len(W0)) || W0 || [u64le(len(Wi)) || Wi ...])
         * where W0 is the WitnessArgs with its lock field zeroed to 65 bytes (85 bytes
         * serialized), and Wi are the remaining same-group witnesses. The final
         * witnesses[0] is the same WitnessArgs with lock = the real signature.
         *
         * Assumes a single script group: all `num_inputs` inputs share this secp lock
         * and witnesses[1..num_inputs] are empty. (The previous code hashed a bare
         * 65-byte placeholder with un-personalized blake2b and emitted a bare sig —
         * both wrong; the secp lock rejected it.)
         */
    @Throws(WalletException::class) fun `signCkbSecp256k1Witness`(`txHashHex`: kotlin.String, `numInputs`: kotlin.UInt, `privateKeyHex`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_sign_ckb_secp256k1_witness(
    
        FfiConverterString.lower(`txHashHex`),FfiConverterUInt.lower(`numInputs`),FfiConverterString.lower(`privateKeyHex`),_status)
}
    )
    }
    

    @Throws(WalletException::class) fun `signMessage`(`messageHex`: kotlin.String, `privateKeyHex`: kotlin.String, `algorithm`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_sign_message(
    
        FfiConverterString.lower(`messageHex`),FfiConverterString.lower(`privateKeyHex`),FfiConverterString.lower(`algorithm`),_status)
}
    )
    }
    

    @Throws(WalletException::class) fun `signTransaction`(`rawTxHex`: kotlin.String, `privateKeyHex`: kotlin.String, `algorithm`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_sign_transaction(
    
        FfiConverterString.lower(`rawTxHex`),FfiConverterString.lower(`privateKeyHex`),FfiConverterString.lower(`algorithm`),_status)
}
    )
    }
    

    @Throws(WalletException::class) fun `verifySignature`(`messageHex`: kotlin.String, `signatureHex`: kotlin.String, `publicKeyHex`: kotlin.String, `algorithm`: kotlin.String): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_verify_signature(
    
        FfiConverterString.lower(`messageHex`),FfiConverterString.lower(`signatureHex`),FfiConverterString.lower(`publicKeyHex`),FfiConverterString.lower(`algorithm`),_status)
}
    )
    }
    

    @Throws(WalletException::class) fun `buildTransaction`(`request`: TransactionRequest): BuiltTransaction {
            return FfiConverterTypeBuiltTransaction.lift(
    uniffiRustCallWithError(WalletException) { _status ->
    UniffiLib.uniffi_wyltekwalletcore_fn_func_build_transaction(
    
        FfiConverterTypeTransactionRequest.lower(`request`),_status)
}
    )
    }
    


